from .profile import Profile
from .empresa import Empresa
from .grado import Grado
from .nivel import Nivel
from .seccion import Seccion
from .catedratico import Catedratico
from .profesion import Profesion
from .material import MaterialClase
from .tarea import Tarea
#from .rol import Rol
from .estudiante import Estudiante
from .asignacion import Asignacion
from .ciclo import Ciclo
from .evento import Evento
from .asignacionEstudiante import AsignacionEstudiante
from .tareaEstudiante import TareaEstudiante